### ISSUE TITLE
README has typo

### ISSUE THREAD

**Issue by deadcoder0904** [Rajesh-Royal/Broprint.js#9] opened 2024-02-04 06:34 UTC
```ts
import { getCurrentBrowserFingerPrint } from "npm i @rajesh896/broprint.js";
```

should be

```ts
import { getCurrentBrowserFingerPrint } from "@rajesh896/broprint.js";
```

**Comment by BenAHammond** [comment] 2024-02-29 00:24
There's [an open PR for this](https://github.com/Rajesh-Royal/Broprint.js/pull/5). Not sure if it was intended or not at this point as its sitting untouched.

**Comment by Rajesh-Royal** [comment] 2024-03-01 08:54
I will approve the PR after review. Thank you.

**Comment by Rajesh-Royal** [comment] 2024-03-01 08:58
@deadcoder0904 @BenAHammond The PR #5 is merged. Thank you.

**Closed as completed by Rajesh-Royal** 2024-03-01 08:58 UTC
